### ISSUE TITLE
Tilføj anbefalede sikkerhedsscripts fra pc-image iso byg

### ISSUE THREAD

**Issue by sunekochhansen** [OS2borgerPC/os2borgerpc-core-scripts#7]
Under byg af iso filerne bliver der kørt en række scripts fra det oprindelige scripts repository [https://github.com/OS2borgerPC/os2borgerpc-scripts](https://github.com/OS2borgerPC/os2borgerpc-scripts)

de scripts der ikke allerede er en del af det nye os2borgerpc-core-scripts repository (dette), skal flyttes hertil og markeres i en speciel kategori.

**Comment by sunekochhansen** [comment]
### OK: scripts refereret fra pc-image der allerede findes her
$SCRIPT_DIR/common/system/apt_periodic_control.sh
$SCRIPT_DIR/os2borgerpc/sikkerhed/polkit_policy_shutdown_suspend.sh
$SCRIPT_DIR/os2borgerpc/sikkerhed/protect_terminal.sh
$SCRIPT_DIR/os2borgerpc/sikkerhed/adjust_settings_access.sh
$SCRIPT_DIR/os2borgerpc/browser/firefox_global_policies.sh
$SCRIPT_DIR/os2borgerpc/browser/browser_set_default.sh
$SCRIPT_DIR/os2borgerpc/sikkerhed/dconf_run_prompt_toggle.sh
$SCRIPT_DIR/os2borgerpc/os2borgerpc/install_okular_and_set_as_standard_pdf_reader.sh
$SCRIPT_DIR/os2borgerpc/desktop/dconf_desktop_background.sh
$SCRIPT_DIR/os2borgerpc/login/dconf_change_login_bg.sh
$SCRIPT_DIR/os2borgerpc/libreoffice/overwrite_libreoffice_config.sh
$SCRIPT_DIR/os2borgerpc/desktop/dconf_a11y.sh
$SCRIPT_DIR/common/system/randomize_jobmanager.sh
$SCRIPT_DIR/common/system/grub_set_password.py
$SCRIPT_DIR/os2borgerpc/udfases/desktop_activate_shortcuts.sh


### MANGLER: scripts refereret fra pc-image der skal tilføjes
$SCRIPT_DIR/os2borgerpc/udfases/dconf_disable_lock_menu.sh" 
$SCRIPT_DIR/os2borgerpc/udfases/dconf_disable_user_switching.sh
$SCRIPT_DIR/os2borgerpc/sikkerhed/dconf_disable_gnome_remote_desktop.sh
$SCRIPT_DIR/os2borgerpc/udfases/lightdm_greeter_setup_scripts.sh
$SCRIPT_DIR/os2borgerpc/os2borgerpc/lightdm_fix_boot_error.sh
$SCRIPT_DIR/os2borgerpc/udfases/set_user_as_default_lightdm_user.sh
$SCRIPT_DIR/os2borgerpc/udfases/remove_new_release_message.sh
$SCRIPT_DIR/images/apt_get_config_set_dpkg_lock_timeout.sh
$SCRIPT_DIR/images/apt_get_config_set_fix_broken.sh
$SCRIPT_DIR/os2borgerpc/printer/allow_superuser_to_manage_cups.sh

**Comment by agnetemoos** [comment]
Tak for oversigten. Jeg har tilføjet tre scripts til core scripts i dag. Hvis I vil flytte resten er det fint med mig.

Her er min arbejdsgang:
- Jeg flytter markdown-filen fra os2borgerpc-community-scripts
- Jeg kopierer scriptet ind fra os2borgerpc-scripts. 

Disse to scripts ligger ikke i os2borgerpc-community-scripts, da de er skjulte. Dvs. markdown er ikke skrevet.
$SCRIPT_DIR/images/apt_get_config_set_dpkg_lock_timeout.sh
$SCRIPT_DIR/images/apt_get_config_set_fix_broken.sh

Jeg er ved at danne mig et overblik over hvilke scripts, jeg vil mene skal være skjulte. Men jeg kan jo tilføje skjult, metadata efterfølgende, hvor det er relevant.

**Comment by sunekochhansen** [comment]
Hej @agnetemoos 

jeg har prøvet at følge din arbejdsgang, vil du ikke reviewe PR ved lejlighed?
https://github.com/OS2borgerPC/os2borgerpc-core-scripts/pull/9
